# Generated by Django 3.1.4 on 2021-01-03 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=40)),
                ('part_inst', models.CharField(max_length=50)),
                ('part_email', models.EmailField(max_length=50)),
                ('part_phone', models.CharField(max_length=12)),
                ('part_DOB', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
