# Generated by Django 3.1.4 on 2021-01-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='part_DOB',
        ),
    ]
