# Generated by Django 3.1.4 on 2021-01-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('UG', 'UnderGraduates'), ('PG', 'PostGraduates'), ('ST', 'Staff'), ('SC', 'School Students')], max_length=2)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
